telegram.bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}

spring.jpa.hibernate.ddl-auto: ${JPA_DDL_AUTO}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
